name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_REPO:${{ github.run_number }} -t $DOCKER_IMAGE_REPO:latest .

      - name: Push Docker image
        run: |
          docker push $DOCKER_IMAGE_REPO:${{ github.run_number }}
          docker push $DOCKER_IMAGE_REPO:latest

      - name: Export IMAGE_TAG
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

  deploy-to-aks:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        # Add a specific version if 'latest' causes issues in the future, e.g., with: version: '1.28.0'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube # This line creates the .kube directory if it doesn't exist
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config # Ensure correct permissions for security

      - name: Update image tag in deployment manifest
        # Ensure the sed command's regex correctly matches your image line.
        # The current sed assumes 'image:' is at the beginning of the line or only matched once.
        run: |
          sed -i "s|image:.*$|image: ${{ env.DOCKER_IMAGE_REPO }}:${{ needs.build-and-push-image.outputs.image_tag }}|" kubernetes/deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml