name: NPM Audit and Issue

on:
  push:
    branches:
      - test_branch

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run npm audit and save results
        run: npm audit --json > audit.json

      - name: Generate audit summary markdown
        run: node .github/scripts/generate-audit-summary.js

      - name: Create GitHub Issue if vulnerabilities found
        id: create_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if grep -q "## Vulnerabilities found" audit-summary.md; then
            ISSUE_URL=$(gh issue create \
              --title "Automated NPM Audit Report $(date +'%Y-%m-%d')" \
              --body-file audit-summary.md \
              --label dependencies,security,automated)
            echo "issue_url=$ISSUE_URL" >> $GITHUB_OUTPUT
          else
            echo "No vulnerabilities found. No issue created."
          fi

      - name: Print created issue link
        if: ${{ steps.create_issue.outputs.issue_url }}
        run: |
          echo "Created issue: ${{ steps.create_issue.outputs.issue_url }}"
